application_name:
  - '1Password 7'
  - 'Alfred 4'
  - 'Docker'
  - 'Dropbox'
  - 'Evernote'
  - 'Flycut'
  - 'Focus'
  - 'Google Chrome'
  - 'iTerm'
  - 'Slack'
  - 'Spectacle'
  - 'Spotify'
  - 'Visual Studio Code'