---
- name: Build localhost
  hosts: localhost
  connection: local

  vars:
    upgrade_homebrew_packages: true
    mas_upgrade_all_apps: true

  tasks:
    - name: Check if Homebrew is already installed in /usr
      stat:
        path: /usr/local/bin/brew
      register: homebrew_local
      tags:
        - brew
        - brew-bundle

    - name: Check if Homebrew is already installed /opt
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_opt
      tags:
        - brew

    - fail:
        msg: Please perform the pre-req's in the README.md
      when: not homebrew_local.stat.exists and not homebrew_opt.stat.exists
      tags:
        - brew

    - name: Install brew bundles
      command: "brew bundle -v --file rearranged_BrewFile"
      when: homebrew_local.stat.exists or homebrew_opt.stat.exists
      tags:
        - brew-bundle

    - name: check if prezto is setup
      stat: path=$HOME/.zprezto
      register: prezto
      tags:
        - prezto

    - name: Clone prezto
      git:
        repo: "https://github.com/sorin-ionescu/prezto.git"
        dest: "$HOME/.zprezto"
      when: not prezto.stat.exists
      tags:
        - prezto

    - name: check if zgen is setup
      stat: path=$HOME/.zgen/zgen.zsh
      register: zgen
      tags:
        - zgen

    - name: include VSCODE extensions vars
      include_vars:
        file: vscode_extensions.yaml
      tags:
        - vscode

    - name: Install VSCode extensions
      command: "code --install-extension {{ item }}"
      with_items:
        - "{{ vscode_ext }}"
      tags:
        - vscode

    - name: Set zsh as default shell
      become: false
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: include Login Packages vars
      include_vars:
        file: login_packages.yml
      tags:
        - login

    - name: Setup Apps to start at login
      shell: loginItems -a "{{ item }}"
      with_items:
        - "{{ login_packages }}"
      tags:
        - login

    - name: Set 24 hour time
      osx_defaults:
        domain: com.apple.menuextra.clock
        key: DateFormat
        type: string
        value: "EEE HH:mm:ss"
      register: restartSystemUIServer
      tags:
        - clock

    - name: restart SystemUIServer
      command: killall SystemUIServer
      when: restartSystemUIServer is defined
      tags:
        - clock
